version: '3.8'

services:
  telegram_bot:
    build: .
    environment:
      - TELEGRAM_TOKEN
      - OPENAI_API_KEY
      - TG_API_ID
      - TG_API_ID_HASH
      - DEBUG
    volumes:
      - ./ggml-model-q4_1.gguf:/app/ggml-model-q4_1.gguf:ro
    command: nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]